#!/bin/sh
set -e

# Runtime user/group management (aligned with v7.4-fpm style, simplified).
# Env vars:
#   PUID (default 82)         | fallback: CUID
#   PGID (default 82)         | fallback: CGID
#   USER_NAME (default www-data) | fallback: CUSER
#   GROUP_NAME (default www-data) | fallback: CGROUP
#   NUMPROCS (default 1)
#   PHP_OPCACHE_PRELOAD (optional)
#   PHP_OPCACHE_FREQ (default 600)

PUID="${PUID:-${CUID:-82}}"
PGID="${PGID:-${CGID:-82}}"
USER_NAME="${USER_NAME:-${CUSER:-www-data}}"
GROUP_NAME="${GROUP_NAME:-${CGROUP:-www-data}}"
NUMPROCS="${NUMPROCS:-1}"
PHP_OPCACHE_PRELOAD="${PHP_OPCACHE_PRELOAD:-}"
PHP_OPCACHE_FREQ="${PHP_OPCACHE_FREQ:-600}"

# Ensure numeric values
case "$PUID" in (*[!0-9]*|'') PUID=82 ;; esac
case "$PGID" in (*[!0-9]*|'') PGID=82 ;; esac

resolve_group() {
    if getent group "$GROUP_NAME" >/dev/null 2>&1; then
        # Name exists: keep it, ignore PGID mismatch to avoid conflicts
        return
    fi
    if getent group "$PGID" >/dev/null 2>&1; then
        GROUP_NAME=$(getent group "$PGID" | cut -d: -f1)
        return
    fi
    addgroup -g "$PGID" "$GROUP_NAME" 2>/dev/null || addgroup "$GROUP_NAME"
}

resolve_user() {
    if getent passwd "$USER_NAME" >/dev/null 2>&1; then
        # Name exists: keep it, ignore PUID mismatch to avoid UID changes
        return
    fi
    if getent passwd "$PUID" >/dev/null 2>&1; then
        USER_NAME=$(getent passwd "$PUID" | cut -d: -f1)
        return
    fi
    adduser -D -u "$PUID" -G "$GROUP_NAME" -s /bin/sh "$USER_NAME" 2>/dev/null || adduser -D -G "$GROUP_NAME" -s /bin/sh "$USER_NAME"
}

resolve_group
resolve_user

# Adjust ownership of writable locations to the resolved uid/gid
RESOLVED_UID=$(getent passwd "$USER_NAME" | cut -d: -f3)
RESOLVED_GID=$(getent group "$GROUP_NAME" | cut -d: -f3)
chown "$RESOLVED_UID":"$RESOLVED_GID" /var/log/php || true
chown "$RESOLVED_UID":"$RESOLVED_GID" /var/www/html || true

# Apply supervisor settings dynamically if config exists
if [ -f /etc/supervisor.d/laravel.ini ]; then
        # Ensure workers run as the resolved user and set numprocs from env
        sed -i -E "s/^user=.*/user=${USER_NAME}/" /etc/supervisor.d/laravel.ini || true
        sed -i -E "s/^numprocs=.*/numprocs=${NUMPROCS}/" /etc/supervisor.d/laravel.ini || true
fi

# Apply OPcache settings from environment (optional)
OPCACHE_INI="/usr/local/etc/php/conf.d/zz-opcache-env.ini"
{
    echo "; Generated by entrypoint at $(date -u)"
    echo "opcache.revalidate_freq=${PHP_OPCACHE_FREQ}"
    if [ -n "${PHP_OPCACHE_PRELOAD}" ]; then
        echo "opcache.preload=${PHP_OPCACHE_PRELOAD}"
        echo "opcache.preload_user=${USER_NAME}"
    fi
} > "${OPCACHE_INI}" 2>/dev/null || true

# Cron file stays root-owned; supervisor logs stay root.

if [ "$#" -eq 0 ]; then
    # Respect Dockerfile CMD default (php -a); set here only if truly no args
    set -- php -a
fi

# If command is explicitly root-only keep root, else drop privileges
case "$1" in
    sh|bash|root-shell)
        exec "$@" ;;
    supervisord)
        # Run supervisor as root; workers drop to specified user via config
        exec "$@" ;;
    *)
        exec su-exec "$USER_NAME":"$GROUP_NAME" "$@" ;;
esac