#!/bin/sh
set -e

# Runtime user/group management (aligned with v7.4-fpm style, simplified).
# Env vars:
#   PUID (default 82)         | fallback: CUID
#   PGID (default 82)         | fallback: CGID
#   USER_NAME (default www-data) | fallback: CUSER
#   GROUP_NAME (default www-data) | fallback: CGROUP
#   NUMPROCS (default 1)
#   PHP_OPCACHE_PRELOAD (optional)
#   PHP_OPCACHE_FREQ (default 600)
#   BROWSCAP_ENABLE (0/1, default 0)
#   BROWSCAP_VARIANT (full|standard|lite, default standard)
#   BROWSCAP_SOURCE_URL (override URL, optional)
#   BROWSCAP_PATH (default /usr/local/etc/php/browscap/browscap.ini)
#   BROWSCAP_TTL (seconds, default 604800 ~ 7 days)
#   BROWSCAP_FORCE_REFRESH (0/1, default 0)

PUID="${PUID:-${CUID:-82}}"
PGID="${PGID:-${CGID:-82}}"
USER_NAME="${USER_NAME:-${CUSER:-www-data}}"
GROUP_NAME="${GROUP_NAME:-${CGROUP:-www-data}}"
NUMPROCS="${NUMPROCS:-1}"
PHP_OPCACHE_PRELOAD="${PHP_OPCACHE_PRELOAD:-}"
PHP_OPCACHE_FREQ="${PHP_OPCACHE_FREQ:-600}"
BROWSCAP_ENABLE="${BROWSCAP_ENABLE:-0}"
BROWSCAP_VARIANT="${BROWSCAP_VARIANT:-standard}"
BROWSCAP_SOURCE_URL="${BROWSCAP_SOURCE_URL:-}"
BROWSCAP_PATH="${BROWSCAP_PATH:-/usr/local/etc/php/browscap/browscap.ini}"
BROWSCAP_TTL="${BROWSCAP_TTL:-604800}"
BROWSCAP_FORCE_REFRESH="${BROWSCAP_FORCE_REFRESH:-0}"

# Ensure numeric values
case "$PUID" in (*[!0-9]*|'') PUID=82 ;; esac
case "$PGID" in (*[!0-9]*|'') PGID=82 ;; esac

resolve_group() {
    if getent group "$GROUP_NAME" >/dev/null 2>&1; then
        # Name exists: keep it, ignore PGID mismatch to avoid conflicts
        return
    fi
    if getent group "$PGID" >/dev/null 2>&1; then
        GROUP_NAME=$(getent group "$PGID" | cut -d: -f1)
        return
    fi
    addgroup -g "$PGID" "$GROUP_NAME" 2>/dev/null || addgroup "$GROUP_NAME"
}

resolve_user() {
    if getent passwd "$USER_NAME" >/dev/null 2>&1; then
        # Name exists: keep it, ignore PUID mismatch to avoid UID changes
        return
    fi
    if getent passwd "$PUID" >/dev/null 2>&1; then
        USER_NAME=$(getent passwd "$PUID" | cut -d: -f1)
        return
    fi
    adduser -D -u "$PUID" -G "$GROUP_NAME" -s /bin/sh "$USER_NAME" 2>/dev/null || adduser -D -G "$GROUP_NAME" -s /bin/sh "$USER_NAME"
}

resolve_group
resolve_user

# Adjust ownership of writable locations to the resolved uid/gid
RESOLVED_UID=$(getent passwd "$USER_NAME" | cut -d: -f3)
RESOLVED_GID=$(getent group "$GROUP_NAME" | cut -d: -f3)
chown "$RESOLVED_UID":"$RESOLVED_GID" /var/log/php || true
chown "$RESOLVED_UID":"$RESOLVED_GID" /var/www/html || true
chown -R "$RESOLVED_UID":"$RESOLVED_GID" /var/log/supervisor 2>/dev/null || true
chown "$RESOLVED_UID":"$RESOLVED_GID" /var/log/cron.log 2>/dev/null || true
chmod 0664 /var/log/cron.log 2>/dev/null || true
chmod 2775 /var/log/php 2>/dev/null || true
chmod g+s /var/log/php 2>/dev/null || true
chmod 2775 /var/log/supervisor 2>/dev/null || true
chmod g+s /var/log/supervisor 2>/dev/null || true
# Normalize permissions of existing files to be group-writable
find /var/log/php -maxdepth 1 -type f -exec chmod 664 {} \; 2>/dev/null || true
find /var/log/supervisor -maxdepth 1 -type f -exec chmod 664 {} \; 2>/dev/null || true

# Ensure group-writable defaults for new files
umask 0002

# Apply supervisor settings dynamically if config exists
if [ -f /etc/supervisor.d/laravel.ini ]; then
        # Ensure workers run as the resolved user and set numprocs from env
        sed -i -E "s/^user=.*/user=${USER_NAME}/" /etc/supervisor.d/laravel.ini || true
        sed -i -E "s/^numprocs=.*/numprocs=${NUMPROCS}/" /etc/supervisor.d/laravel.ini || true
fi

# Apply OPcache settings from environment (optional)
OPCACHE_INI="/usr/local/etc/php/conf.d/zz-opcache-env.ini"
{
    echo "; Generated by entrypoint at $(date -u)"
    echo "opcache.revalidate_freq=${PHP_OPCACHE_FREQ}"
    if [ -n "${PHP_OPCACHE_PRELOAD}" ]; then
        echo "opcache.preload=${PHP_OPCACHE_PRELOAD}"
        echo "opcache.preload_user=${USER_NAME}"
    fi
} > "${OPCACHE_INI}" 2>/dev/null || true

# Optionally configure browscap dynamically
maybe_setup_browscap() {
    case "${BROWSCAP_ENABLE}" in
        1|true|TRUE|on|ON|yes|YES) : ;;
        *) return 0 ;;
    esac

    # Determine source URL if not provided
    if [ -z "${BROWSCAP_SOURCE_URL}" ]; then
        case "${BROWSCAP_VARIANT}" in
            full) SRC_SUFFIX="Full_PHP_BrowsCapINI" ;;
            lite) SRC_SUFFIX="Lite_PHP_BrowsCapINI" ;;
            *) SRC_SUFFIX="PHP_BrowsCapINI" ;;
        esac
        BROWSCAP_SOURCE_URL="https://browscap.org/stream?q=${SRC_SUFFIX}"
    fi

    BCP_DIR=$(dirname "${BROWSCAP_PATH}")
    mkdir -p "${BCP_DIR}" || true

    # Refresh logic
    if [ "${BROWSCAP_FORCE_REFRESH}" = "1" ] && [ -f "${BROWSCAP_PATH}" ]; then
        rm -f "${BROWSCAP_PATH}" 2>/dev/null || true
    fi

    NOW=$(date +%s 2>/dev/null || echo 0)
    NEED_DL=1
    if [ -f "${BROWSCAP_PATH}" ]; then
        MTIME=$(stat -c %Y "${BROWSCAP_PATH}" 2>/dev/null || echo 0)
        AGE=$(( NOW - MTIME ))
        if [ "$AGE" -lt "${BROWSCAP_TTL}" ]; then
            NEED_DL=0
        fi
    fi

    if [ "$NEED_DL" -eq 1 ]; then
        TMP_FILE="${BROWSCAP_PATH}.tmp"
        # Conditional download using -z to avoid redownload if not modified
        curl -fsSL -z "${BROWSCAP_PATH}" -o "${TMP_FILE}" "${BROWSCAP_SOURCE_URL}" || true
        if [ -s "${TMP_FILE}" ]; then
            mv "${TMP_FILE}" "${BROWSCAP_PATH}" || true
        else
            rm -f "${TMP_FILE}" || true
        fi
    fi

    # Ensure perms
    chown "$RESOLVED_UID":"$RESOLVED_GID" "${BROWSCAP_PATH}" 2>/dev/null || true
    chmod 0644 "${BROWSCAP_PATH}" 2>/dev/null || true

    # Write ini fragment
    BCP_INI="/usr/local/etc/php/conf.d/zz-browscap-env.ini"
    {
      echo "; Generated by entrypoint at $(date -u)"
      echo "browscap=${BROWSCAP_PATH}"
    } > "${BCP_INI}" 2>/dev/null || true
}

# Cron file stays root-owned; supervisor logs stay root.

# Run optional setups that depend on resolved uid/gid
maybe_setup_browscap

if [ "$#" -eq 0 ]; then
    # Respect Dockerfile CMD default (php -a); set here only if truly no args
    set -- php -a
fi

# If command is explicitly root-only keep root, else drop privileges
case "$1" in
    sh|bash|root-shell)
        exec "$@" ;;
    supervisord)
        # Run supervisor as root; workers drop to specified user via config
        exec "$@" ;;
    *)
        exec su-exec "$USER_NAME":"$GROUP_NAME" "$@" ;;
esac