[supervisord]
nodaemon=true
[program:worker]
process_name=%(program_name)s_%(process_num)02d
command=/var/www/html/artisan queue:work --timeout=60 --tries=5
autostart=true
autorestart=true
user=%(ENV_USER_NAME)s
; numprocs will be overridden dynamically by entrypoint based on NUMPROCS env (default 1)
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/supervisor.log
environment=NUMPROCS="%(ENV_NUMPROCS)s"
[program:cron]
command=/usr/sbin/crond -f
autostart=true
autorestart=true
redirect_stderr=true
